title: Blue Jays Bistro
email: bluejaysbistro@gmail.com
description: >-
  A culinary experience; coming soon!
baseurl: ""
url: "https://bluejaysbistro.com/"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
jekyll-minifier:
  uglifier_args:
    harmony: true
feed:
  tags: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
