title: Monique Mosher
email: monique@moniquemosher.com
description: >-
  Faith Based Evidential Psychic Medium Inner Child Coach
baseurl: ""
url: "https://moniquemosher.com"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

date_format: "%b %-d, %Y"

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

jekyll-minifier:
  uglifier_args:
    harmony: true

feed:
  tags: false
