---
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@39dc1e003e0c99ee009eecca4773bb6aa4935ce2" # v0.11.1
    permissions:
      contents: write

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@39dc1e003e0c99ee009eecca4773bb6aa4935ce2" # v0.11.1
    permissions: read-all
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
