---
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@ef07cf67ff3b59d701ca4ebb5670f8579b0b0303" # v0.10.33
    permissions:
      contents: write

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@ef07cf67ff3b59d701ca4ebb5670f8579b0b0303" # v0.10.33
    permissions: read-all
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
